[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
TextAnalysis = "a2db99b7-8b79-58f8-94bf-bbc811eef33d"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf" 